### ISSUE TITLE
Unfortunately COVID WATCH app has stopped in Android device

### ISSUE THREAD

**Issue by karunakaranpt** [covid19risk/covidwatch-android#79]
COVID WATCH has been installed in my Android device successfully. I got the following error when opening the App.

Android device specifications:
```
Model: Asus Zenfone Max
Android version: 6.0.1
```

Error in Android device:
`"Unfortunately COVID WATCH app has stopped in Android device"
`
Error in Android Studio Logcat:
```
2020-04-16 17:46:35.042 11816-11846/org.covidwatch.tags.android E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: org.covidwatch.tags.android, PID: 11816
    java.lang.NoClassDefFoundError: com.google.common.base.CharMatcher
        at com.google.common.base.Splitter.on(Splitter.java:127)
        at io.grpc.internal.GrpcUtil.<clinit>(GrpcUtil.java:203)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.<clinit>(AbstractManagedChannelImplBuilder.java:84)
        at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:48)
        at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:27)
        at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:73)
        at com.google.firebase.firestore.remote.GrpcCallProvider.initChannel(com.google.firebase:firebase-firestore@@21.4.2:113)
        at com.google.firebase.firestore.remote.GrpcCallProvider.lambda$initChannelTask$6(com.google.firebase:firebase-firestore@@21.4.2:256)
        at com.google.firebase.firestore.remote.GrpcCallProvider$$Lambda$5.call(com.google.firebase:firebase-firestore@@21.4.2)
        at com.google.android.gms.tasks.zzv.run(Unknown Source)
        at com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0(com.google.firebase:firebase-firestore@@21.4.2:54)
        at com.google.firebase.firestore.util.ThrottledForwardingExecutor$$Lambda$1.run(com.google.firebase:firebase-firestore@@21.4.2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
2020-04-16 17:46:44.944 11816-11845/org.covidwatch.tags.android W/Firestore: (21.4.2) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
    
    This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

```

**Comment by nkumarcc** [comment]
What branch is this?

**Comment by karunakaranpt** [comment]
develop branch.

**Comment by haydenridd** [comment]
I've isolated this issue to being specific to OS version 6 on Android. I can replicate in the simulator, and as soon as you go to OS 7+ this issue goes away.
